tulibraries/cob_datapipeline

README.md

Documentation only PR, rebased after pushes to master over last week.

merging changes from deploy-prep pr

---

scripts/ingest_marc.sh
scripts/ingest_marc_multi.sh

When rbenv is installed it will use the .ruby version defined in
tul_cob/.ruby-version

Assume rbenv is installed.

---

.travis.yml
.travis/deploy-qa.sh

Please god let this be the last one in the setup of CI/CD via travis.

removing EOF from deploy bash script

---

almaoai_harvest.py
processtrajectlog.py
task_ingestmarc.py
task_ingestsftpmarc.py

Putting the traject log in the log dir with a .log extension so that logrotate will pick it up.

use explicit logdir var, fix oai endpoint url

---

scripts/ingest_databases.sh
task_ingest_databases.py
tests/conftest.py
tests/tul_cob_az_reindex_dag_test.py
tul_cob_az_reindex_dag.py

REF BL-868
Refactors the az_dag to use a new executable to do the ingest.  Also the new executable fixes a bug where az documents were not being deleted.

[BL-868] Use cob_az_index executable to ingest az files.

---

scripts/ingest_web_content.sh
task_ingest_web_content.py
task_slackpost.py
tests/conftest.py
tests/tul_cob_web_context_index_dag_test.py
tul_cob_web_content_index_dag.py

* Add initial web_content dag work
* Make script executable
* Add tests.

Create web content dag (#88)

---

tests/tul_cob_az_reindex_dag_test.py

* Test dag schedule is configurable.
* Test we set env["SOLR_AZ_URL"] when calling az dag bash ingest script.

Add AZ tests.

---

scripts/ingest_web_content.sh
task_ingest_databases.py
task_ingest_web_content.py
tests/task_ingest_web_content_test.py
tul_cob_web_content_index_dag.py
tul_cob_web_content_index_sc_dag.py

Depends on: https://github.com/tulibraries/cob_web_index/pull/30

Add new sc specific web content ingest dag.

---

tul_cob_web_content_index_sc_dag.py

* Fixes sc web content dag always reporting that pre docs count is 0.

Add swap step to web content sc dag.

---

tul_cob_az_reindex_sc_dag.py

Without this solr doesn't correctly report original number of docs
(i.e. the original doc count is always 0).

Swap the collection that alias points to for AZ SC Dag.

---

Pipfile
Pipfile.lock
sc_catalog_full_reindex_dag.py
scripts/sc_archive_s3_data.sh
tests/conftest.py

some small tweaks to solrcloud full catalog indexing dag.

Sc full catalog tweaks

---

qa_sc_catalog_oai_index_dag.py

Thanks @sensei100 for pointing out the fix.

Fix reference to wrong id.

---

sc_xml_parse.py

Also uses text interpolation for easier reading.

Fix failing http request.

---

Pipfile.lock
prod_sc_catalog_oai_index_dag.py
qa_sc_catalog_oai_index_dag.py
stage_sc_catalog_oai_index_dag.py

Uses a caching version of perform_xml_lookup method.

Use harvest.perform_xml_lookup_with_cache

---

Pipfile
Pipfile.lock

lxml 4.5.0 is breaking cob datapipelines.

[DEVO-41] Pin lxml version.

---

prod_sc_catalog_full_reindex_dag.py
prod_sc_catalog_oai_index_dag.py
qa_sc_catalog_full_reindex_dag.py
qa_sc_catalog_oai_index_dag.py
stage_sc_catalog_full_reindex_dag.py
stage_sc_catalog_oai_index_dag.py

- Get rid of unnecessary parameters and update endpoint

Refactor solr_commit task

---

cob_datapipeline/prod_sc_catalog_oai_index_dag.py
cob_datapipeline/stage_sc_catalog_oai_index_dag.py

* Fix stage and prod oai harvest fail to get S3 files.

Update master with latest qa changes.

---

cob_datapipeline/scripts/sc_ingest_marc.sh

Make script backwards compatible.

Use default ingest command.

---

cob_datapipeline/prod_sc_catalog_oai_index_dag.py
cob_datapipeline/qa_sc_catalog_oai_index_dag.py
cob_datapipeline/stage_sc_catalog_oai_index_dag.py

Also passes full environment variables into bash operators.

Updates oai harvests to not do ingest and deletes concurrently.

---

cob_datapipeline/preproduction_catalog_oai_harvest_dag.py
cob_datapipeline/prod_catalog_oai_harvest_dag.py
tests/preproduction_catalog_oai_harvest_dag.py
tests/prod_catalog_oai_harvest_dag_test.py

- Updates dag names for qa and prod oai_harvest dags

BL-1198 Rename oai_harvest dags

---

cob_datapipeline/catalog_full_reindex_dag.py
cob_datapipeline/catalog_safety_check.py
cob_datapipeline/preproduction_catalog_oai_harvest_dag.py
tests/catalog_full_reindex_dag_test.py
tests/catalog_safety_check_test.py
tests/conftest.py

* Adds safety_check task to harvest and full reindexing
* Renames ambiguous task.

Add safety check for harvest and full reindex dag.

---

cob_datapipeline/prod_catalog_oai_harvest_dag.py

Task that defines the namespace used in s3 was in full reindex and preprod oai dags was updated in [#190](https://github.com/tulibraries/cob_datapipeline/pull/190). This applies those same changes to the prod oai dag.

Align prod oai dag task for s3 namespace

---

Pipfile
Pipfile.lock
cob_datapipeline/catalog_create_collection.py
cob_datapipeline/catalog_full_reindex_dag.py
tests/catalog_create_collection_test.py
tests/conftest.py

* Use CATALOG_PRE_PRODUCTION_SOLR_COLLECTION value for collection name
if present.
* Create collection name from configset + cob_index version + timestamp
* Skip collection creation if already present.
* Minor cleanup.
* Use static aliases (get solr num docs and always now what collection is the next pre-prod).

BL-1194 Update full reindex collection creation and naming.

---

.circleci/config.yml

We need to be specific when doing a tagged release deployment.

BL-1203: Use tagged repo in cob_datapipeline prod deploy.

---

cob_datapipeline/catalog_safety_check.py

* Use None as default when running safety check.

Fix undefined CATALOG_PRE_PRODUCTION_SOLR_COLLECTION.

---

cob_datapipeline/catalog_full_reindex_dag.py
tests/catalog_full_reindex_dag_test.py

Also fix the source prefix for prepare alma data to use the orignal data
namespace.

Prepare alma data depends on prepare boundwiths

---

cob_datapipeline/catalog_full_reindex_dag.py

Airflow has two solr connections set up, SOLRCLOUD and SOLRCLOUD-WRITER.
Slorcloud writer exists because we were seeing indexing errors when
running traject updates through the load balancer. SolrCloud-Writer
establishes a direct connection to a single solrcloud IP address,
bypassing the load balancer.
Full Reindex and other dags started to use SOLRCLOUD-WRITER for all
actions. This PR changes that behavior in only the Full Reindex dag to
use the load balanced SOLRCLOUD connection for API calls and generic
queries comgin from Airflow.
This will fix an error with the create_collection method as used in the
Full reindex dag.

Update full reindex dag use of solr connections

---

cob_datapipeline/catalog_safety_check.py

#207 moved these methods to `helpers.py`, but didn't to remove this file.

Remove file of functions moved to helpers

---

cob_datapipeline/prod_catalog_oai_harvest_dag.py

Renames the dag to be consistent with preprod and full reindex.

Tweak prod oai variable names

---

doc/full-reindex-process.md

Adds documentation of the steps required to complete the full reindex from Alma Export to having hte new data live in production.
Would love feedback if this seems like the right amount of context of if more is needed to use this as a guide for the process.

Document steps required for full reindex process

---

cob_datapipeline/catalog_preproduction_oai_harvest_dag.py

Pre production and production harvest dags are relying on a changing time vs.
a time which is fixed per execution.
This PR fixes this issue for the pre-production harvest dag by replacing
it with the execution_date macro which is provided by airflow as a fixed
time of execution.

BL-1251: Fix time bug for pre-production harvest.

---

cob_datapipeline/catalog_preproduction_oai_harvest_dag.py

* Instead of outright deletes will flip suppression field on record.
Depends on: tulibraries/cob_index#127

Use supress switch on deletes.

---

cob_datapipeline/prod_sc_az_reindex_dag.py
cob_datapipeline/qa_sc_az_reindex_dag.py
tests/prod_sc_az_reindex_dag_test.py

DEVO-62: Add alias and collection cleanup to reindexing dags

DEVO-62: Update prod az indexing dag with qa changes.

---

cob_datapipeline/prod_sc_web_content_reindex_dag.py
cob_datapipeline/qa_sc_web_content_reindex_dag.py
tests/prod_sc_web_content_reindex_dag_test.py

Update prod web content indexing dag with latest qa changes.
DEVO-62: Add alias and collection cleanup to reindexing dags

DEVO-62: Update prod web-content indexing dag.

---

cob_datapipeline/dspace_harvest_dag.py
cob_datapipeline/operators/batch_s3_to_sftp_operator.py
tests/dspace_harvest_test.py
variables.json

Bl 1343 update dspace dag

---

cob_datapipeline/dspace_harvest_dag.py
variables.json

- Updates harvest task to use setSpec as an included_set

BL-1344 Update harvest task

---

cob_datapipeline/operators/batch_s3_to_sftp_operator.py

- Add .xml extension to files in sftp server

BL-1347 update s3 to sftp task

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

- minor improvements to identifier mappings and several other elements to account for the differences between SWORD-ingested ETDs and migrated ETDs from CONTENTdm
- update to XSLT 2.0 in order to use replace() function with a regular expression

update ETD transform

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

Another attempt to fix the date variable, which was working fine before. 
Alicia is checking on the source data to see if a record with multiple dates can be identified on the DSpace side.

more date transform troubleshooting

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

- testing to see if removing thesisYear variable helps

remove thesisYear variable

---

Pipfile
Pipfile.lock

* Also update airflow version to make sure all is still working.
* Also move packages to dev so that all is controlled from airflow app
on deployment.

Update tulflow version.

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

- Update MARC LDR and 007 fields due to Alma loading and validation errors

update MARC LDR and 007

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

- Add currentDate function to generate bytes 00-05 of the 008 field, per Carla's feedback
- clean up some comments, variables, and spacing

Add currentDate to 008 field

---

cob_datapipeline/catalog_full_reindex_dag.py
cob_datapipeline/prod_sc_az_reindex_dag.py
cob_datapipeline/prod_sc_web_content_reindex_dag.py
cob_datapipeline/qa_sc_az_reindex_dag.py
cob_datapipeline/qa_sc_web_content_reindex_dag.py
tests/conftest.py
variables.json

- Updates replication factor to be 4 instead of 2
- Updates docker-dev submodule to latest commit

DEVO-319 Update replication factor

---

cob_datapipeline/catalog_move_alma_sftp_to_s3_dag.py
cob_datapipeline/catalog_production_oai_harvest_dag.py
doc/catalog-search-oai-harvest-process.md

- Updates links in the doc file to match the correct dag
- Updates catalog dag to fix pylint warnings
- Removes extra spaces in harvest dag

Fixes some syntax and typo errors

---

cob_datapipeline/prod_sc_az_reindex_dag.py
tests/prod_sc_az_reindex_dag_test.py

DEVO-364: Use execution_date macro to generate collection name.

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

- add 506 field for open access
- add 500 field for note describing supplemental files

Add fields to DSpace ETD transform

---

cob_datapipeline/prod_az_reindex_dag.py
cob_datapipeline/qa_az_reindex_dag.py
tests/prod_az_reindex_dag_test.py
tests/qa_az_reindex_dag_test.py

* Keeping this a draft in case actual issue was the fact that prod_sc_az_index was anabled.

DEVO-417: revert use execution_date for collection name.

---

cob_datapipeline/catalog_move_alma_sftp_to_s3_dag.py
cob_datapipeline/operators/batch_s3_to_sftp_operator.py
cob_datapipeline/operators/batch_sftp_to_s3_operator.py

- Don't pass unrecognized args to batch operators

DEVO-362 Airflow 2 updates

---

cob_datapipeline/dspace_harvest_dag.py
cob_datapipeline/operators/batch_s3_to_sftp_operator.py

- Need to add provide_context to init args

DEVO-362 Additional arg updates

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

Reverts tulibraries/cob_datapipeline#666

Revert "BL-1609: remove <collection> tag from transform"

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

Found one more instance of / that I needed to change to # in MARC 008

BL-1609 update transform (again)

---

cob_datapipeline/files/TEU_XOAItoMARCXML.xsl

add collection name to DSpace transform

---

cob_datapipeline/catalog_full_reindex_dag.py
cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
cob_datapipeline/catalog_production_oai_harvest_dag.py
cob_datapipeline/notifiers.py
cob_datapipeline/prod_az_reindex_dag.py
cob_datapipeline/prod_web_content_reindex_dag.py
cob_datapipeline/qa_az_reindex_dag.py
cob_datapipeline/qa_web_content_reindex_dag.py
tests/catalog_full_reindex_dag_test.py

* Use collection specific slack notifier for success.
* Move success notifications to last task.

DEVO-890: Add collection specific slack notifier.

---

.github/airflow-constraints-requirements.txt

This is an experiment to see if we can get dependabot to use a requirements.txt file that uses the airflow constraints file.

Dependabot experiment

---

cob_datapipeline/catalog_full_reindex_dag.py
cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
cob_datapipeline/catalog_production_oai_harvest_dag.py
cob_datapipeline/tasks/task_solr_get_num_docs.py

This will resolve some deprecation warnings we are getting.

Update SimpleHttpOperator to HttpOperator

---

cob_datapipeline/prod_web_content_reindex_dag.py

Sorry, I forgot to add the variable to the task in the last PR.

Add variable to task

---

.circleci/config.yml
.circleci/scripts/build-requirements.sh
.circleci/scripts/compare_dependencies.sh
.gitignore
Makefile
Pipfile
Pipfile.lock
README.md

This PR will make circle builds fail if a dependency is added that does not match airflow-constraints.

Automatically check against airflow constraints in circle.

---

cob_datapipeline/catalog_full_reindex_dag.py
tests/catalog_full_reindex_dag_test.py

Trying to to use sub_list inside a template causes an error.
This PR moves that functionality to a task.

BL-1763: Fix template error

---

cob_datapipeline/catalog_full_reindex_dag.py

tojson is a templating method that needs to be called from inside the template.

BL-1763: Move tojson call inside the template.

---

cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
cob_datapipeline/catalog_production_oai_harvest_dag.py
cob_datapipeline/scripts/ingest_marc.sh
tests/catalog_preproduction_oai_harvest_dag_test.py
tests/catalog_production_oai_harvest_dag_test.py

- **Update ingest script to handle larger lists of files.**
- **Add a task execution timeout.  Fail if any task takes longer than 10 hours.**

update ingest script to handle big lists

---

cob_datapipeline/backup_collections_dag.py
tests/backup_collections_dag_test.py

- **Add delete old solr backups task.**

DEVO 1166 create solr backup delete dag
