tulibraries/cob_datapipeline

- almaoai_harvest.py
- almasftp_fetch.py
- processtrajectlog.py
- scripts/ingest_marc.sh
- scripts/ingest_marc_multi.sh
- task_ingestmarc.py
- task_ingestsftpmarc.py
- tul_cob_fullreindex_dag.py
- tul_cob_pipeline_dag.py
pushing things towards production
linting
parameterized solr URL for ingest
better error handling processing traject log
break oai xml into single lines
oai pmh more robust error handling 
always set  traject skipped count even if there were none
traject skipstr count is different than the individual error messages, so count those instead
traject logging
don’t try to ingest a nonexistent marcfile
better tracking of what marcfile we’re working with e.g. when moving old files
> Bl 841 reindex skip supressed

- scripts/ingest_marc.sh
- scripts/ingest_marc_multi.sh
.bashrc isn't being called by the airflow bashoperator, so let's do it explicitly,
Add some informational printouts for future debugging.
> Fix ingest rubies

- almaoai_harvest.py
- almasftp_fetch.py
- processtrajectlog.py
- scripts/ingest_marc.sh
- task_ingestmarc.py
- task_ingestsftpmarc.py
- tul_cob_fullreindex_dag.py
- tul_cob_pipeline_dag.py
Create variable for OAI publishing interval
Set OAI “from” date to account for the OAI publishing interval
Set explicit OAI “until” date
Don’t move forward harvest date until we actually retrieve records
Move traject log once we’ve read it so that we don’t re-read it again
Add comments to dag file
Make sure key vars are set on startup
Set max_active_runs so that we only have one dag run at a time
os.remove works on paths, not file objects (obvs)
General pep8 linting
> Date clobber on OAI ingest (temporary until date issues are sorted out)

- almaoai_harvest.py
A bug I introduced in the last patch trying to be more clean about date management.
> Save the T-Z formatted date instead of Python formatted date

- tul_cob_pipeline_dag.py
- The Airflow tul_cob schedule needs be as follows, using UTC: 3:00, 
9:00, 15:00, 21:00.
- This update is based on the assumption that timezone should be UTC for cob_datapipeline. This can be edited to EST if needed. 
- Note from Christina: not merge into QA until variables pr is up too
> Updated start_date

- almasftp_fetch.py
- parsesftpdump.py
- scripts/git_pull_tul_cob.sh
- scripts/ingest_marc.sh
- scripts/ingest_marc_multi.sh
- tul_cob_fullreindex_dag.py
Debug printout cmd line vars in shell scripts. 
Increase timeout for sftp fetch because it ran long one time. 
Remove the solr replication tasks because we're not going that route.
> Refactor parsesftpdump to move old dumps. Added step to DAG. 

- task_almasftp.py
Setting this variable in task creation is causing it to get recreated
every time we try to edit it.  And, this seems to be causing an error
where task fails under certain conditions.
> Remove almafullreindex_inprogress variable.

- qa_sc_catalog_oai_index_dag.py
Using slash as our delimeter is causing None to be returned instead of a list of files.
> Use empty delimeter when listing s3 files.

- prod_sc_catalog_full_reindex_dag.py
- qa_sc_catalog_full_reindex_dag.py
- stage_sc_catalog_full_reindex_dag.py
This variable is necessary to skip items that only include missing/lost/etc. process types.  The slorcloud dags don't currently pass this variable in, so the records are being ingested instead of skipped.
> Add TRAJECT_FULL_REINDEX variable to solrcloud dags

- prod_sc_catalog_oai_index_dag.py
- qa_sc_catalog_oai_index_dag.py
- stage_sc_catalog_oai_index_dag.py
The update from date needs to be envrionment specific in order to work in the current dag.
This commit makes this variable environment specific.
> BL-1110 Fix update from date oai harvest broken

- prod_sc_catalog_oai_index_dag.py
- qa_sc_catalog_oai_index_dag.py
- stage_sc_catalog_oai_index_dag.py
* Currently, there is no commit at the end of the ingest task so the slack numbers are not accurate.
* This adds a commit task before the slack post for more accuracy in reporting
> BL-1113 Add commit step before get number solr docs step.

- prod_sc_catalog_full_reindex_dag.py
- qa_sc_catalog_full_reindex_dag.py
- stage_sc_catalog_full_reindex_dag.py
- tests/prod_sc_catalog_full_reindex_dag_test.py
- tests/qa_sc_catalog_full_reindex_dag_test.py
- tests/stage_sc_catalog_full_reindex_dag_test.py
- Currently, there is no commit at the end of the ingest task so the slack numbers are not accurate.
- This adds a commit task before the slack post for more accuracy in reporting
> Bl 1107 add commit task

- cob_datapipeline/alma_electronic_notes_dag.py
- tests/alma_electronic_notes_dag_test.py
Fixes S3_TO_FTP task broken.
Replaces task with dynamic list of task.
> Add s3_to_sftp task per alma notes type.

- cob_datapipeline/catalog_move_alma_sftp_to_s3_dag.py
Was a hold over from when the custom Operator was defined in this file. No longer required.
> Remove extraneous base hook import

- .circleci/config.yml
- README.md
* Deploy to qa on merges to master branch.
* Deploy to production on release.
* Keeps requires approval for deploys (Further guards against unintentional deploys).
> BL-1204 Update qa workflow.

- cob_datapipeline/helpers.py
- tests/helpers_test.py
`configset` and `cob_index_version` should already be parsed in the Jinja template.
Otherwise, they are null.
> Fix collection name Jinja template.

- .circleci/config.yml
This means the each change to a repo does not run the entire airflow playbook, but only the parts that update dags. Needs to run the jumphost role so it can connect.
> Limit the CD to only deploy dags

- doc/full-reindex-process.md
CATALOG_PRE_PRODUCTION_SOLR_COLLECTION needs to be set to None at the beginning of the full_reindex dag run or the safety check will fail.
> Add more information for CATALOG_PRE_PRODUCTION_SOLR_COLLECTION

- cob_datapipeline/scripts/sc_ingest_marc.sh
REF DEVO-229
Sometimes there are many files that need to be
ingested/deleted/suppressed and the task fails halfway in and then
starts right back from the beginning.
This change would avoid re-ingesting or deleting/suppressing a file that
has already been processed in an earlier failed task. Thus potentially
minimizing recovery time.
This change would also have the added benefit that in the case where
recovery is not possible because of a corrupt file, then that corrupt
file would be first on the list which can potentially reduce debugging
time.
> DEVO-229: Move processed files to another folder

- cob_datapipeline/scripts/sc_ingest_marc.sh
We don't have a straight forward way to update file paths for processed files
in full reindex context.  This is a quick fix to avoid error were we try
to s3 mv a file to itself (i.e. source and destination are equal).
TODO: Alma SFTP dump should go to  a subfolder so that we can easily add the
same efficiency step we use in harvest context to the full reindex context.
> Skip moving s3 files when src and dest are equal.

- cob_datapipeline/prod_sc_az_reindex_dag.py
- cob_datapipeline/prod_sc_web_content_reindex_dag.py
The prod dags for the az and web-content indexing dags are sharing the same variable for keeping track of collections.  This is potentially dangerous because while both the qa and prod dags run simultaneously this could cause qa to mistakenly delete a prod collection.
> DEVO-286: Use prod specific variables to keep track of collections and aliases.

- cob_datapipeline/files/TEU_XOAItoMARCXML.xsl
Updating date variable to attempt to fix Saxon error in DAG run; it appears there is a record that contains more than one date, so I have updated the xpath to only look for 1st occurrence of date issued
Error message:
A sequence of more than one item is not allowed as the first argument of fn:substring() ("2016", "2018")
> troubleshooting transform error

- cob_datapipeline/files/TEU_XOAItoMARCXML.xsl
- Updates xpath for date variable; turns out the change from xslt1.0 to xslt2.0 makes the value-of element more "grabby," so it was pulling in all the dates instead of just one.
Thanks for your patience, this should really be the last one! (fingers crossed)
> Update xpath for date variable

- cob_datapipeline/files/TEU_XOAItoMARCXML.xsl
- Update ORCID mapping such that only the 1st value is mapped, if multiple values are present
- Update 100 $0 output such that the (orcid) prefix is only generated if the identifier is not an http URI
> update ORCID mapping

- cob_datapipeline/helpers.py
- cob_datapipeline/tasks/xml_parse.py
We've been running into a lot of encoding/decoding issues with full
reindex dag.
The xml for indexing files are very big one line files, so I think always
enforcing utf-8 encoding will help prevent this parsing errors with
lxml.
> Always enforce utf-8 encoding.

- cob_datapipeline/files/TEU_XOAItoMARCXML.xsl
- removes <collection> parent tag from xsl transform. 
Airflow already generates a <collection> parent tag. Multiple <collection> tags are causing MARCXML import to fail in Alma. Testing this to see if it will address the problem.
> BL-1609: remove <collection> tag from transform

- cob_datapipeline/files/TEU_XOAItoMARCXML.xsl
Update DSpace transform to use # instead of / to represent a blank space in MARC LDR, 006, and 008 fields, as Alma does not recognize / upon import.
> BL-1609 update transform

- cob_datapipeline/catalog_full_reindex_dag.py
Now that the bw files are no longer in the root directory, we need to
use the correct path that references the
ALMASFTP_S3_ORIGINAL_BW_DATA_NAMESPACE variable.
> BL-1634: Update bw path to use correct folder.

- .circleci/config.yml
There is something in the playbook that the dags tasks need that it isn't getting with our previous configuration.  This is a temporary solution to get the needed changes to QA, but we should narrow down which tasks actually need to be run as a next step.
> Add the airflow tag

- cob_datapipeline/alma_electronic_notes_dag.py
- cob_datapipeline/boundwith_move_alma_sftp_to_s3_dag.py
- cob_datapipeline/catalog_move_alma_sftp_to_s3_dag.py
- cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
- cob_datapipeline/catalog_production_oai_harvest_dag.py
- cob_datapipeline/dspace_harvest_dag.py
- cob_datapipeline/prod_az_reindex_dag.py
- cob_datapipeline/prod_web_content_reindex_dag.py
- cob_datapipeline/qa_az_reindex_dag.py
- cob_datapipeline/qa_web_content_reindex_dag.py
According to this documentation: [Templates reference — Airflow Documentation](https://airflow.apache.org/docs/apache-airflow/stable/templates-ref.html), the data_interval_start variable is described as Start of the data interval ([pendulum.DateTime](https://pendulum.eustace.io/docs/#introduction)). Pendulum is an additional package that needs to be imported into each DAG.  
As a first pass at fixing this, I am going to import Pendulum and set the start_date for all of our dags to be pendulum.datetime(2018, 12, 13, tz="UTC"). That is the preferred way of defining dates with Airflow 2.
> BL-1708 Import pendulum in all dags

- cob_datapipeline/boundwith_move_alma_sftp_to_s3_dag.py
- cob_datapipeline/catalog_move_alma_sftp_to_s3_dag.py
A bug in airflow causes the wrong permission to be added to folders created by the sftp provider.
> BL-1707: Fix wrong permission in created sftp folder.

- Pipfile
- Pipfile.lock
- tests/operators/solr_api/delete_collection_test.py
The failures in the tests were all related to the expected log output changing.  It doesn't seem that the actual methods had any breaking changes.
> Update airflow to 2.8.1

- cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
- cob_datapipeline/catalog_production_oai_harvest_dag.py
- cob_datapipeline/helpers.py
- tests/catalog_preproduction_oai_harvest_dag_test.py
- tests/helpers_test.py
* Also moves method for choosing a branch to a shared location so that it can be shared by pre-production and production dag.
* Also updates the branch choosing method to return a list of tasks to run vs just the name of the first task in a branch to run.
* Also updates the trigger rules so that tasks are't blocked by upstream skips.
> BL-1897: Allow production oai harvest to handle no records.

- cob_datapipeline/catalog_full_reindex_dag.py
If the task fails because of not enough resources, the retry may resolve the problem.
> BL-1763: Add retries to tasks that run in parallel.

- cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
- cob_datapipeline/catalog_production_oai_harvest_dag.py
We made an update to the marc ingesting script that requires the list of files to be processed be passed in via a DATA environment variable.
This change was required to allow for concurrent indexing.
This commit updates the harvest dags to set DATA env variable as required by the new script.
> Fix harvest dags not working.

- cob_datapipeline/catalog_production_oai_harvest_dag.py
This env variable is required in order to iterate over deleted and updated marc xml files.
> Add missing data env to update/delete harvest task.

- cob_datapipeline/catalog_preproduction_oai_harvest_dag.py
- cob_datapipeline/catalog_production_oai_harvest_dag.py
- cob_datapipeline/scripts/ingest_marc.sh
- tests/catalog_preproduction_oai_harvest_dag_test.py
- tests/catalog_production_oai_harvest_dag_test.py
- **Revert "update ingest script to handle big lists (#1680)"**
- **update execution timeouts defaults for harvest tasks.**
The space in the bash commad are require (unless the bash script is templated) and the changes did not work to fix original isssue.
We are still keeping the timeout failure.
> revert big list update

- cob_datapipeline/files/TEU_XOAItoMARCXML.xsl
- Change MARC encoding level in LDR from "K" to "7" per updates to OCLC Bibliographic Formats and Standards
> update encoding level for ETD transform

- cob_datapipeline/boundwith_move_alma_sftp_to_s3_dag.py
- cob_datapipeline/catalog_move_alma_sftp_to_s3_dag.py
According to docs we need to use ssh_conn_id not sft_conn_id when initializing that SFTPHook task.
See: https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/_api/airflow/providers/sftp/operators/sftp/index.html
> Use ssh_conn_id vs sftp_conn_id in SFTPHook call.
